#pragma once

#define UXPLAY_AV_SYNC_LEGACY_REBASE 0
#define UXPLAY_AV_SYNC_ABSOLUTE_NTP 1
#define UXPLAY_AV_SYNC_SESSION_ANCHOR 2

#ifndef UXPLAY_AV_SYNC_STRATEGY
#define UXPLAY_AV_SYNC_STRATEGY UXPLAY_AV_SYNC_SESSION_ANCHOR
#endif
